PYTHON=python2.7 -B

testar:
	@echo "Testando progunit.py"
	@$(PYTHON) progunit_tests.py
	@echo "Testando eccheck.py"
	@$(PYTHON) eccheck_tests.py
	@echo "Testando tspcheck.py"
	@$(PYTHON) tspcheck_tests.py
